<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="0" total="16" passed="13">
  <reporter-output>
  </reporter-output>
  <suite name="Suite B" duration-ms="875" started-at="2016-05-18T15:28:53Z" finished-at="2016-05-18T15:28:54Z">
    <groups>
    </groups>
    <test name="Test 1" duration-ms="586" started-at="2016-05-18T15:28:53Z" finished-at="2016-05-18T15:28:54Z">
      <class name="com.qtpselenium.framework.datadriven.suiteB.Test1">
        <test-method status="PASS" signature="initLogs()[pri:0, instance:com.qtpselenium.framework.datadriven.suiteB.Test1@2286778]" name="initLogs" is-config="true" duration-ms="4" started-at="2016-05-18T20:58:53Z" finished-at="2016-05-18T20:58:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initLogs -->
        <test-method status="PASS" signature="test1(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.datadriven.suiteB.Test1@2286778]" name="test1" duration-ms="318" started-at="2016-05-18T20:58:53Z" data-provider="suiteBDataProvider" finished-at="2016-05-18T20:58:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col3=C33, Col2=C22, Col1=C11, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="test1(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.datadriven.suiteB.Test1@2286778]" name="test1" duration-ms="78" started-at="2016-05-18T20:58:53Z" data-provider="suiteBDataProvider" finished-at="2016-05-18T20:58:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col3=C34, Col2=C23, Col1=C12, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="test1(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.datadriven.suiteB.Test1@2286778]" name="test1" duration-ms="72" started-at="2016-05-18T20:58:53Z" data-provider="suiteBDataProvider" finished-at="2016-05-18T20:58:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col3=C35, Col2=C24, Col1=C13, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- com.qtpselenium.framework.datadriven.suiteB.Test1 -->
    </test> <!-- Test 1 -->
    <test name="Test 2" duration-ms="190" started-at="2016-05-18T15:28:54Z" finished-at="2016-05-18T15:28:54Z">
      <class name="com.qtpselenium.framework.datadriven.suiteB.Test2">
        <test-method status="PASS" signature="initLogs()[pri:0, instance:com.qtpselenium.framework.datadriven.suiteB.Test2@6b09bb57]" name="initLogs" is-config="true" duration-ms="2" started-at="2016-05-18T20:58:54Z" finished-at="2016-05-18T20:58:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initLogs -->
        <test-method status="PASS" signature="test2(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.datadriven.suiteB.Test2@6b09bb57]" name="test2" duration-ms="48" started-at="2016-05-18T20:58:54Z" data-provider="suiteBDataProvider" finished-at="2016-05-18T20:58:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col4=C43, Col3=C33, Col2=C22, Col1=C11, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="SKIP" signature="test2(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.datadriven.suiteB.Test2@6b09bb57]" name="test2" duration-ms="55" started-at="2016-05-18T20:58:54Z" data-provider="suiteBDataProvider" finished-at="2016-05-18T20:58:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col4=C44, Col3=C34, Col2=C23, Col1=C12, Runmode=N, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the testTest2inside the suite SuiteB]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the testTest2inside the suite SuiteB
	at com.qtp.selenium.framework.datadriven.DataDrivenFramework.TestBase.validateRunmodes(TestBase.java:68)
	at com.qtpselenium.framework.datadriven.suiteB.Test2.test2(Test2.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="test2(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.datadriven.suiteB.Test2@6b09bb57]" name="test2" duration-ms="48" started-at="2016-05-18T20:58:54Z" data-provider="suiteBDataProvider" finished-at="2016-05-18T20:58:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col4=C45, Col3=C35, Col2=C24, Col1=C13, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
      </class> <!-- com.qtpselenium.framework.datadriven.suiteB.Test2 -->
    </test> <!-- Test 2 -->
    <test name="Test 3" duration-ms="76" started-at="2016-05-18T15:28:54Z" finished-at="2016-05-18T15:28:54Z">
      <class name="com.qtpselenium.framework.datadriven.suiteB.Test3">
        <test-method status="PASS" signature="initLogs()[pri:0, instance:com.qtpselenium.framework.datadriven.suiteB.Test3@67784306]" name="initLogs" is-config="true" duration-ms="3" started-at="2016-05-18T20:58:54Z" finished-at="2016-05-18T20:58:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initLogs -->
        <test-method status="SKIP" signature="test3(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.datadriven.suiteB.Test3@67784306]" name="test3" duration-ms="36" started-at="2016-05-18T20:58:54Z" data-provider="suiteBDataProvider" finished-at="2016-05-18T20:58:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col4=, Col3=, Col2=, Col1=, Runmode=, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the testTest3inside the suite SuiteB]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the testTest3inside the suite SuiteB
	at com.qtp.selenium.framework.datadriven.DataDrivenFramework.TestBase.validateRunmodes(TestBase.java:68)
	at com.qtpselenium.framework.datadriven.suiteB.Test3.test3(Test3.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
      </class> <!-- com.qtpselenium.framework.datadriven.suiteB.Test3 -->
    </test> <!-- Test 3 -->
  </suite> <!-- Suite B -->
  <suite name="Suite A" duration-ms="1945" started-at="2016-05-18T15:28:49Z" finished-at="2016-05-18T15:28:51Z">
    <groups>
    </groups>
    <test name="Test 1" duration-ms="1120" started-at="2016-05-18T15:28:49Z" finished-at="2016-05-18T15:28:50Z">
      <class name="com.qtpselenium.framework.datadriven.suiteA.Test1">
        <test-method status="PASS" signature="initLogs()[pri:0, instance:com.qtpselenium.framework.datadriven.suiteA.Test1@4566e5bd]" name="initLogs" is-config="true" duration-ms="37" started-at="2016-05-18T20:58:49Z" finished-at="2016-05-18T20:58:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initLogs -->
        <test-method status="FAIL" signature="test1(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.datadriven.suiteA.Test1@4566e5bd]" name="test1" duration-ms="120" started-at="2016-05-18T20:58:50Z" data-provider="suiteADataProvider" finished-at="2016-05-18T20:58:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col3=C33, Col2=C22, Col1=C11, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [B1] but found [A1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.qtpselenium.framework.datadriven.suiteA.Test1.test1(Test1.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
nnFailure 2 of 2:njava.lang.AssertionError: expected [A] but found [A2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [B1] but found [A1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.qtpselenium.framework.datadriven.suiteA.Test1.test1(Test1.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
nnFailure 2 of 2:njava.lang.AssertionError: expected [A] but found [A2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.qtpselenium.framework.datadriven.suiteA.Test1.test1(Test1.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="FAIL" signature="test1(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.datadriven.suiteA.Test1@4566e5bd]" name="test1" duration-ms="97" started-at="2016-05-18T20:58:50Z" data-provider="suiteADataProvider" finished-at="2016-05-18T20:58:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col3=C34, Col2=C23, Col1=C12, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [B1] but found [A1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.qtpselenium.framework.datadriven.suiteA.Test1.test1(Test1.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
nnFailure 2 of 2:njava.lang.AssertionError: expected [A] but found [A2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [B1] but found [A1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.qtpselenium.framework.datadriven.suiteA.Test1.test1(Test1.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
nnFailure 2 of 2:njava.lang.AssertionError: expected [A] but found [A2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.qtpselenium.framework.datadriven.suiteA.Test1.test1(Test1.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="FAIL" signature="test1(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.datadriven.suiteA.Test1@4566e5bd]" name="test1" duration-ms="75" started-at="2016-05-18T20:58:50Z" data-provider="suiteADataProvider" finished-at="2016-05-18T20:58:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col3=C35, Col2=C24, Col1=C13, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [B1] but found [A1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.qtpselenium.framework.datadriven.suiteA.Test1.test1(Test1.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
nnFailure 2 of 2:njava.lang.AssertionError: expected [A] but found [A2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: expected [B1] but found [A1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.qtpselenium.framework.datadriven.suiteA.Test1.test1(Test1.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
nnFailure 2 of 2:njava.lang.AssertionError: expected [A] but found [A2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.qtpselenium.framework.datadriven.suiteA.Test1.test1(Test1.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- com.qtpselenium.framework.datadriven.suiteA.Test1 -->
    </test> <!-- Test 1 -->
    <test name="Test 2" duration-ms="374" started-at="2016-05-18T15:28:50Z" finished-at="2016-05-18T15:28:50Z">
      <class name="com.qtpselenium.framework.datadriven.suiteA.Test2">
        <test-method status="PASS" signature="initLogs()[pri:0, instance:com.qtpselenium.framework.datadriven.suiteA.Test2@2038ae61]" name="initLogs" is-config="true" duration-ms="13" started-at="2016-05-18T20:58:50Z" finished-at="2016-05-18T20:58:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initLogs -->
        <test-method status="PASS" signature="test2(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.datadriven.suiteA.Test2@2038ae61]" name="test2" duration-ms="111" started-at="2016-05-18T20:58:50Z" data-provider="suiteADataProvider" finished-at="2016-05-18T20:58:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col4=C43, Col3=C33, Col2=C22, Col1=C11, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="test2(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.datadriven.suiteA.Test2@2038ae61]" name="test2" duration-ms="97" started-at="2016-05-18T20:58:50Z" data-provider="suiteADataProvider" finished-at="2016-05-18T20:58:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col4=C44, Col3=C34, Col2=C23, Col1=C12, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="test2(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.datadriven.suiteA.Test2@2038ae61]" name="test2" duration-ms="92" started-at="2016-05-18T20:58:50Z" data-provider="suiteADataProvider" finished-at="2016-05-18T20:58:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col4=C45, Col3=C35, Col2=C24, Col1=C13, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
      </class> <!-- com.qtpselenium.framework.datadriven.suiteA.Test2 -->
    </test> <!-- Test 2 -->
    <test name="Test 3" duration-ms="156" started-at="2016-05-18T15:28:50Z" finished-at="2016-05-18T15:28:50Z">
      <class name="com.qtpselenium.framework.datadriven.suiteA.Test3">
        <test-method status="PASS" signature="initLogs()[pri:0, instance:com.qtpselenium.framework.datadriven.suiteA.Test3@3327bd23]" name="initLogs" is-config="true" duration-ms="2" started-at="2016-05-18T20:58:50Z" finished-at="2016-05-18T20:58:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initLogs -->
        <test-method status="SKIP" signature="test3(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.datadriven.suiteA.Test3@3327bd23]" name="test3" duration-ms="96" started-at="2016-05-18T20:58:50Z" data-provider="suiteADataProvider" finished-at="2016-05-18T20:58:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col5=C53, Col4=C43, Col3=C33, Col2=C22, Col1=C11, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the testTest3inside the suite SuiteA]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the testTest3inside the suite SuiteA
	at com.qtp.selenium.framework.datadriven.DataDrivenFramework.TestBase.validateRunmodes(TestBase.java:68)
	at com.qtpselenium.framework.datadriven.suiteA.Test3.test3(Test3.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
      </class> <!-- com.qtpselenium.framework.datadriven.suiteA.Test3 -->
    </test> <!-- Test 3 -->
    <test name="Test 4" duration-ms="224" started-at="2016-05-18T15:28:50Z" finished-at="2016-05-18T15:28:51Z">
      <class name="com.qtpselenium.framework.datadriven.suiteA.Test4">
        <test-method status="PASS" signature="test4(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.datadriven.suiteA.Test4@5383967b]" name="test4" duration-ms="67" started-at="2016-05-18T20:58:51Z" data-provider="suiteADataProvider" finished-at="2016-05-18T20:58:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col1=C11, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method status="PASS" signature="test4(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.datadriven.suiteA.Test4@5383967b]" name="test4" duration-ms="89" started-at="2016-05-18T20:58:51Z" data-provider="suiteADataProvider" finished-at="2016-05-18T20:58:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col1=C12, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
      </class> <!-- com.qtpselenium.framework.datadriven.suiteA.Test4 -->
    </test> <!-- Test 4 -->
  </suite> <!-- Suite A -->
  <suite name="My Project" duration-ms="0" started-at="2016-05-18T15:28:55Z" finished-at="2016-05-18T15:28:55Z">
    <groups>
    </groups>
  </suite> <!-- My Project -->
</testng-results>
