<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Lenovo-PC" name="com.qtpselenium.suiteB.TestCase_B1" tests="4" failures="0" timestamp="18 May 2016 15:28:00 GMT" time="0.011" errors="1">
  <testcase name="testcaseB1" time="0.002" classname="com.qtpselenium.suiteB.TestCase_B1">
    <error type="org.testng.SkipException" message="RunMode for Test data B1 is set as No1">
      <![CDATA[org.testng.SkipException: RunMode for Test data B1 is set as No1
	at com.qtpselenium.suiteB.TestCase_B1.testcaseB1(TestCase_B1.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1221)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- testcaseB1 -->
  <testcase name="testcaseB1" time="0.002" classname="com.qtpselenium.suiteB.TestCase_B1"/>
  <testcase name="testcaseB1" time="0.004" classname="com.qtpselenium.suiteB.TestCase_B1"/>
  <testcase name="testcaseB1" time="0.003" classname="com.qtpselenium.suiteB.TestCase_B1"/>
</testsuite> <!-- com.qtpselenium.suiteB.TestCase_B1 -->
