<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="26962" started-at="2016-03-08T16:18:41Z" finished-at="2016-03-08T16:19:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="26962" started-at="2016-03-08T16:18:41Z" finished-at="2016-03-08T16:19:08Z">
      <class name="Core_WebDriver_DataDriven_Framework.TestReports.TestReports">
        <test-method status="FAIL" signature="verifytitle()[pri:0, instance:Core_WebDriver_DataDriven_Framework.TestReports.TestReports@75bd9247]" name="verifytitle" duration-ms="18879" started-at="2016-03-08T21:48:41Z" finished-at="2016-03-08T21:49:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at Core_WebDriver_DataDriven_Framework.TestReports.TestReports.verifytitle(TestReports.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifytitle -->
        <test-method status="PASS" signature="screenshot(org.testng.ITestResult)[pri:0, instance:Core_WebDriver_DataDriven_Framework.TestReports.TestReports@75bd9247]" name="screenshot" is-config="true" duration-ms="8057" started-at="2016-03-08T21:49:00Z" finished-at="2016-03-08T21:49:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifytitle status=FAILURE method=TestReports.verifytitle()[pri:0, instance:Core_WebDriver_DataDriven_Framework.TestReports.TestReports@75bd9247] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshot -->
      </class> <!-- Core_WebDriver_DataDriven_Framework.TestReports.TestReports -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
